-- StudyPal study materials — PostgreSQL.
--
-- The second migration of the PostgreSQL era (SP-V2-003). Adds the two tables
-- the document ingestion pipeline needs: `materials` (one row per uploaded file)
-- and `material_chunks` (the retrieval-ready text that was extracted from it).
--
-- Applied by `npm run migrate` (scripts/migrate.mjs), inside a transaction, once.
-- Forward-only: there is no down migration. See docs/database-architecture.md.
--
-- DELIBERATELY NOT HERE: any embedding or vector column, and the pgvector
-- extension. SP-V2-003 ends at "chunks are persisted"; embedding them is
-- SP-V2-004. The shape below is chosen so that ticket is a pure ADD COLUMN plus
-- an index — `material_chunks` already has the stable identity (material_id,
-- chunk_index) an embedding row would need to hang off, so nothing here has to
-- be restructured to make room for one.
--
-- Also still not created: study_plans, study_plan_tasks, exams, exam_questions,
-- exam_attempts, attempt_answers, learning_events. Same reason as in 001 — a
-- table with no code reading it is a guess about a future requirement rather
-- than a schema, and tests/schema.test.js asserts by name that none exist.

-- ── materials ────────────────────────────────────────────────────────────────
--
-- One row per uploaded document, created the moment the bytes are safely on
-- disk and updated as processing progresses. The row is the material's identity
-- as far as the API is concerned: `storage_key` never leaves the backend.
--
-- IMPORTANT: ownership here is as weak as it is everywhere else in StudyPal.
-- `user_id` is a real foreign key, but the identity behind it is an
-- unauthenticated username claim (S1 in docs/security-baseline.md). Anyone who
-- knows a username can upload materials as that user and read them back. The FK
-- makes ownership *checkable*; it does not make it *trustworthy*.
CREATE TABLE materials (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

  -- CASCADE, matching questions.user_id: a material is meaningless without the
  -- student it belongs to, and deleting a user must actually delete their data.
  -- Note that this cascade reaches material_chunks transitively but NOT the
  -- stored files — deleting a user through SQL alone would orphan bytes on disk.
  -- Nothing does that today (the API has no user-deletion endpoint), and the
  -- material delete path removes the file explicitly; it is recorded as a known
  -- limitation in docs/material-processing.md rather than papered over with a
  -- trigger that shells out to the filesystem.
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,

  -- The client's own filename, kept for display only. It is echoed back by the
  -- API and NEVER used to build a filesystem path: see storage_key below. The
  -- value is untrusted and may contain slashes, "..", control characters or
  -- 4 KB of nonsense, so it is length-bounded here as well as in validation.
  original_filename TEXT NOT NULL,

  -- The internal key the storage layer uses to find the bytes. Generated by
  -- the backend (a UUID plus an extension derived from the *validated* type),
  -- never derived from anything the client sent. UNIQUE because it identifies
  -- one object in the store, and because a duplicate would mean two materials
  -- believing they own the same bytes — one of them would then delete the
  -- other's file.
  --
  -- The CHECK is the schema-level half of path-traversal defence. The
  -- application generates these keys and src/storage/local-storage.service.js
  -- validates them again on the way in and out, but a key that reached this
  -- column with a slash or a ".." in it would be a filesystem escape waiting
  -- for a code path that trusts the database. Belt and braces, cheaply.
  storage_key TEXT NOT NULL,

  -- The type the backend DECIDED the file is, after checking extension and
  -- content — not the Content-Type the client claimed. Constrained to the two
  -- formats this iteration supports so an unsupported material cannot be
  -- represented at all.
  mime_type TEXT NOT NULL,

  -- Bytes actually written to storage. Positive: a zero-byte upload has no
  -- text in it and must never become `ready` (§17), so it is rejected before a
  -- row exists.
  file_size BIGINT NOT NULL,

  -- The processing lifecycle. A CHECK constraint rather than a PostgreSQL ENUM
  -- type, matching the convention 001 established for every other constrained
  -- value in this schema: adding a state to a CHECK is one migration that
  -- rewrites no rows, whereas ALTER TYPE ... ADD VALUE cannot run inside a
  -- transaction block on older servers and cannot remove a value at all. The
  -- set is small and application-owned, so the type system buys little here.
  --
  --   uploaded   bytes are stored, nothing has been extracted yet
  --   processing extraction/chunking is in flight
  --   ready      text was extracted, chunked and persisted — usable
  --   failed     processing gave up; error_message says why, safely
  --
  -- `ready` is a claim the API makes to clients, so it is only ever written in
  -- the same transaction that persists the chunks (see
  -- src/materials/material.repository.js). There is no path that marks a
  -- material ready without chunks behind it.
  status TEXT NOT NULL DEFAULT 'uploaded',

  -- Pages, when the format has the concept and the parser reported it. NULL for
  -- plain text, which has no pages, and NULL rather than a guess if a PDF
  -- parser cannot say. Never 0 for a document that parsed.
  page_count INTEGER,

  -- Why processing failed, in the sanitised form the API is willing to show a
  -- client. Parser internals, stack traces and filesystem paths are logged
  -- server-side and never written here — see src/materials/material.service.js.
  error_message TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT materials_storage_key_key UNIQUE (storage_key),

  CONSTRAINT materials_status_valid
    CHECK (status IN ('uploaded', 'processing', 'ready', 'failed')),

  -- Same explicit trim set as users_username_not_blank and
  -- questions_question_not_blank, for the same two reasons: bare btrim() strips
  -- SPACES ONLY, so a tab-only filename would satisfy a constraint called "not
  -- blank"; and \x0B is how E'' spells vertical tab (E'' has no \v escape, so
  -- writing \v would put a literal letter "v" in the set).
  CONSTRAINT materials_original_filename_not_blank
    CHECK (btrim(original_filename, E' \t\n\r\f\x0B') <> ''),

  -- 512 is far above any real filename and far below the point where a TEXT
  -- column full of junk becomes a storage problem. Validation rejects these
  -- earlier with a useful message; this stops a future code path that skips it.
  CONSTRAINT materials_original_filename_bounded
    CHECK (char_length(original_filename) <= 512),

  -- The path-traversal guard described above: printable, no separators, no
  -- parent references, no leading dot. Deliberately narrow — the generator
  -- produces "<uuid>.pdf" and nothing else needs to fit.
  CONSTRAINT materials_storage_key_safe
    CHECK (storage_key ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'
           AND storage_key NOT LIKE '%..%'),

  -- Only what this iteration can actually process. PDF and plain text; §8.
  CONSTRAINT materials_mime_type_supported
    CHECK (mime_type IN ('application/pdf', 'text/plain')),

  CONSTRAINT materials_file_size_positive CHECK (file_size > 0),

  -- A parsed document has at least one page. NULL means "not applicable or not
  -- reported", which is a different statement from 0.
  CONSTRAINT materials_page_count_positive
    CHECK (page_count IS NULL OR page_count > 0),

  -- The invariant that makes `status` worth trusting: a failure must carry a
  -- reason, and a success must not carry one. Without this a material could sit
  -- in `failed` with no explanation for the client, or in `ready` with a stale
  -- error from an earlier attempt still attached.
  CONSTRAINT materials_error_message_matches_status CHECK (
    (status = 'failed' AND error_message IS NOT NULL)
    OR (status <> 'failed' AND error_message IS NULL)
  )
);

-- ── material_chunks ──────────────────────────────────────────────────────────
--
-- The extracted text, split into retrieval-sized pieces. Deterministic: the
-- same bytes and the same configuration produce the same chunks with the same
-- indexes, which is what makes the chunking testable and makes re-processing a
-- material idempotent rather than a source of drift.
CREATE TABLE material_chunks (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

  -- CASCADE is load-bearing here, not a convenience: DELETE /api/materials/:id
  -- deletes the material row and relies on this to take the chunks with it, so
  -- there is no application code that could forget. tests/materials/ asserts it
  -- at the SQL level rather than only through the API.
  material_id BIGINT NOT NULL REFERENCES materials (id) ON DELETE CASCADE,

  -- Position in the document, 0-based and contiguous. 0-based because it is an
  -- offset into a sequence rather than a human-facing ordinal, and because the
  -- chunker's loop index is the natural source of truth — renumbering it to
  -- start at 1 would add an off-by-one for no reader's benefit.
  chunk_index INTEGER NOT NULL,

  -- The chunk text itself. TEXT, not JSONB: it is prose, not structure.
  --
  -- This is the column SP-V2-004 will sit an embedding beside. Note what is
  -- NOT here: no `embedding vector(n)`, no `tsvector`, no summary. Adding the
  -- first of those later is an ALTER TABLE plus an index and touches nothing
  -- else in this table.
  content TEXT NOT NULL,

  -- The page this chunk came from, when the extractor could say. NULL for
  -- plain text and for any PDF whose page boundaries could not be recovered —
  -- §13 is explicit that a NULL is better than an invented page number, since
  -- a wrong citation is worse than an absent one.
  page_number INTEGER,

  -- Denormalised char_length(content). Stored rather than computed because the
  -- status endpoint and the chunking tests both want it per-chunk, and because
  -- it makes a mismatch between the chunker's arithmetic and what was actually
  -- written a checkable condition (the CHECK below) rather than a silent one.
  char_count INTEGER NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Ordering is part of the data, so a duplicate index is a corrupt document,
  -- not a tolerable retry artefact. This also gives the (material_id,
  -- chunk_index) lookup its index for free — see the index section below.
  CONSTRAINT material_chunks_material_index_key UNIQUE (material_id, chunk_index),

  CONSTRAINT material_chunks_index_non_negative CHECK (chunk_index >= 0),

  -- A chunk with no meaningful text is not a chunk. §16 requires non-empty
  -- chunks, and §17 requires that a document producing none of them fails
  -- rather than becoming an empty `ready` material; this makes the first of
  -- those a database rule. Same explicit trim set as everywhere else.
  CONSTRAINT material_chunks_content_not_blank
    CHECK (btrim(content, E' \t\n\r\f\x0B') <> ''),

  -- char_count must actually be the content's length. The chunker computes it
  -- from the same string it stores, so a violation means a bug between
  -- computing and writing — exactly the kind of drift a CHECK is cheap at
  -- catching and a comment is useless against.
  CONSTRAINT material_chunks_char_count_matches
    CHECK (char_count = char_length(content)),

  CONSTRAINT material_chunks_page_number_positive
    CHECK (page_number IS NULL OR page_number > 0)
);

-- ── indexes ──────────────────────────────────────────────────────────────────
--
-- ONE, and only one. The same rule 001 set: an index has to serve a query that
-- exists in the code today, because every index costs write throughput and disk
-- and an unused one is pure loss. tests/materials/schema.test.js asserts the
-- exact list on both tables, so adding another fails a test and prompts the
-- justification comment.
--
-- What the constraints above already index, and therefore what is deliberately
-- NOT repeated here:
--
--   materials.id                              PK
--   materials.storage_key                     UNIQUE — the storage-layer lookup
--   material_chunks.id                        PK
--   (material_chunks.material_id, chunk_index) UNIQUE
--
-- That last one is the important freebie: it serves the ordered read of a
-- material's chunks (`WHERE material_id = $1 ORDER BY chunk_index`) and the
-- chunk-count aggregate, so §29's "index chunk ordering" needs no separate
-- index. The per-material ownership check (`WHERE id = $1 AND user_id = $2`) is
-- served by the PK index on materials.id — with a unique match on id, filtering
-- one row by user_id is free.

-- Serves GET /api/materials?username=… — the list endpoint, and the only query
-- on these tables that neither the PK nor a UNIQUE constraint already covers:
--   WHERE user_id = $1 ORDER BY created_at DESC, id DESC
-- Equality column first, then the sort column, so PostgreSQL finds the user's
-- rows and walks them already ordered without a sort step. Exactly the shape of
-- idx_questions_user_created, for exactly the same query shape. DESC is written
-- explicitly to match the query even though PostgreSQL can scan an ASC index
-- backwards. This is also §29's "index material ownership".
CREATE INDEX idx_materials_user_created ON materials (user_id, created_at DESC);

-- ── comments ─────────────────────────────────────────────────────────────────
--
-- Kept in the database so `\d+ materials` in psql explains the non-obvious
-- columns without anyone having to find this file.
COMMENT ON TABLE materials IS
  'One row per uploaded study document. Ownership is via an unauthenticated username claim — see docs/security-baseline.md S1.';
COMMENT ON COLUMN materials.storage_key IS
  'Backend-generated key for the object store. NEVER derived from the client filename, and never exposed through the API.';
COMMENT ON COLUMN materials.original_filename IS
  'The client''s filename, for display only. Untrusted; never used to build a filesystem path.';
COMMENT ON COLUMN materials.mime_type IS
  'The type the backend determined after validating extension and content — not the Content-Type the client claimed.';
COMMENT ON COLUMN materials.status IS
  'uploaded → processing → ready, or → failed. `ready` is only written in the same transaction that persists the chunks.';
COMMENT ON TABLE material_chunks IS
  'Retrieval-ready text extracted from a material. Deterministic: same bytes plus same config produce the same chunks. Embeddings are deferred to SP-V2-004.';
COMMENT ON COLUMN material_chunks.page_number IS
  'Source page when the extractor could determine it, NULL otherwise. Never an invented page number.';
